### ISSUE TITLE
FabricPlaceholderAPI support

### ISSUE THREAD

**Issue by Niketats** [axieum/chatter#15]
Add possibility to use placeholders in chat formatting

https://github.com/Patbox/FabricPlaceholderAPI

**Comment by axieum** [comment]
Hi @Niketats,

Thanks for the suggestion! I've had a close look into this, but it appears that it would probably warrant a rewrite of how placeholders are handled.

I've refactored the Styling module to allow for easy support of adding new mod integrations. Right now, I've added LuckPerms placeholder support directly in #14.

Thanks,
Axieum.
