### ISSUE TITLE
Disable specific discord messages

### ISSUE THREAD

**Issue by Setadokalo** [axieum/chatter#22]
**Is your feature request related to a problem? Please describe.**
In-Game Events get really spammy, really fast. I'd like to not have the chat channel filled to the brim with "server started! server stopped! server started! server stopped! server started! server stopped! server started! server stopped!"

**Describe the solution you'd like**
either by removing the entries from the config file or setting them to an empty string, disable creating embeds for events with no embed structure in the config.

**Comment by axieum** [comment]
Hi @Setadokalo,

You can set it to `null` and that message won't occur, e.g.

```json
"started": null,
```

I'll document this on the wiki.

**Comment by axieum** [comment]
I have updated the wiki, thanks for pointing this out.
